[package]
name = "wasm-kinnemed"
version = "0.1.0"
authors = ["Jorge Hernandez <jorgeenanin@gmail.com>"]
edition = "2018"
repository = "https://github.com/jorgehc1/wasm-kinnemed"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"